version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hopskipchallenge
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate db:seed && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/HopSkipChallenge"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db_data:
